using System;
using System.Collections.Generic;
using System.Linq;
using GuildAdventure.Game.Save;
namespace GuildAdventure.Game.Battle
{
 public sealed class BattleTriggerContext{public string actionId,sourceId,actionSourceId,targetId,skillId;public int hitIndex;public string judgement;public double actualHpLoss;public bool blocked,targetDied;public TriggerActionContext actionContext;}
 public sealed class BattleTriggerDispatch{public TriggerEvent trigger;public BattleTriggerContext context;public List<TriggerRegistration> registrations=new List<TriggerRegistration>();}
 public static class BattleEffectLifecycle
 {
  public static List<BattleTriggerDispatch> DispatchResolvedHitEvents(ResolvedHitSaveRecord hit,IEnumerable<TriggerRegistration> registrations,IReadOnlyDictionary<string,int> fixedOrder,string skillId=null,TriggerActionContext actionContext=null,bool blocked=false,bool targetDied=false,BattleSnapshotSaveRecord snapshot=null){if(hit==null)throw new ArgumentNullException(nameof(hit));var result=new List<BattleTriggerDispatch>();if(string.Equals(hit.judgement,"MISS",StringComparison.OrdinalIgnoreCase)){Add(result,hit,registrations,fixedOrder,TriggerEvent.ON_EVADE,skillId,actionContext,blocked,targetDied);return result;}Add(result,hit,registrations,fixedOrder,TriggerEvent.ON_HIT_DEALT,skillId,actionContext,blocked,targetDied);Add(result,hit,registrations,fixedOrder,TriggerEvent.ON_HIT_RECEIVED,skillId,actionContext,blocked,targetDied);if(snapshot!=null)AddAllyAttack(result,hit,registrations,fixedOrder,skillId,actionContext,snapshot);if(string.Equals(hit.judgement,"CRITICAL",StringComparison.OrdinalIgnoreCase))Add(result,hit,registrations,fixedOrder,TriggerEvent.ON_CRITICAL,skillId,actionContext,blocked,targetDied);if(blocked)Add(result,hit,registrations,fixedOrder,TriggerEvent.ON_BLOCK,skillId,actionContext,blocked,targetDied);if(hit.actualHpLoss>0)Add(result,hit,registrations,fixedOrder,TriggerEvent.ON_DAMAGE_DEALT,skillId,actionContext,blocked,targetDied);if(targetDied)Add(result,hit,registrations,fixedOrder,TriggerEvent.ON_DEATH,skillId,actionContext,blocked,targetDied);return result;}
  static void AddAllyAttack(List<BattleTriggerDispatch> output,ResolvedHitSaveRecord hit,IEnumerable<TriggerRegistration> registrations,IReadOnlyDictionary<string,int> fixedOrder,string skillId,TriggerActionContext actionContext,BattleSnapshotSaveRecord snapshot){var source=snapshot.actors?.Find(x=>x.actorId==hit.sourceId);if(source==null||string.IsNullOrWhiteSpace(source.teamId))return;var resolved=TriggerRuntime.Resolve(registrations,TriggerEvent.ON_ALLY_ATTACK,fixedOrder).Where(r=>!string.Equals(r.ownerId,source.actorId,StringComparison.Ordinal)).Where(r=>{var owner=snapshot.actors.Find(x=>x.actorId==r.ownerId);return owner!=null&&owner.alive&&owner.hp>0&&string.Equals(owner.teamId,source.teamId,StringComparison.Ordinal);}).ToList();if(resolved.Count==0)return;output.Add(new BattleTriggerDispatch{trigger=TriggerEvent.ON_ALLY_ATTACK,context=Context(hit,skillId,actionContext),registrations=resolved});}
  public static BattleTriggerDispatch DispatchEvent(TriggerEvent trigger,string sourceId,string targetId,IEnumerable<TriggerRegistration> registrations,IReadOnlyDictionary<string,int> fixedOrder,string actionId=null,string skillId=null,TriggerActionContext actionContext=null,string actionSourceId=null){var context=new BattleTriggerContext{actionId=actionId,sourceId=sourceId,actionSourceId=string.IsNullOrWhiteSpace(actionSourceId)?sourceId:actionSourceId,targetId=targetId,skillId=skillId,actionContext=actionContext};return new BattleTriggerDispatch{trigger=trigger,context=context,registrations=ResolveForEvent(registrations,trigger,fixedOrder,sourceId,targetId)};}
  public static BattleTriggerDispatch DispatchResolvedHit(ResolvedHitSaveRecord hit,IEnumerable<TriggerRegistration> registrations,IReadOnlyDictionary<string,int> fixedOrder){var all=DispatchResolvedHitEvents(hit,registrations,fixedOrder);return all.Count>0?all[0]:new BattleTriggerDispatch{trigger=TriggerEvent.ON_HIT_DEALT,context=Context(hit)};}
  static void Add(List<BattleTriggerDispatch> output,ResolvedHitSaveRecord hit,IEnumerable<TriggerRegistration> registrations,IReadOnlyDictionary<string,int> fixedOrder,TriggerEvent trigger,string skillId,TriggerActionContext actionContext,bool blocked,bool targetDied){output.Add(new BattleTriggerDispatch{trigger=trigger,context=Context(hit,skillId,actionContext,blocked,targetDied),registrations=ResolveForEvent(registrations,trigger,fixedOrder,hit.sourceId,hit.targetId)});}
  static List<TriggerRegistration> ResolveForEvent(IEnumerable<TriggerRegistration> registrations,TriggerEvent trigger,IReadOnlyDictionary<string,int> fixedOrder,string sourceId,string targetId){var resolved=TriggerRuntime.Resolve(registrations,trigger,fixedOrder);string owner=null;switch(trigger){case TriggerEvent.ON_HIT_RECEIVED:case TriggerEvent.ON_EVADE:case TriggerEvent.ON_BLOCK:case TriggerEvent.ON_DEATH:case TriggerEvent.ON_STATUS_APPLIED:case TriggerEvent.ON_FATAL_DAMAGE:owner=targetId;break;case TriggerEvent.ON_USE:case TriggerEvent.ON_HIT_DEALT:case TriggerEvent.ON_DAMAGE_DEALT:case TriggerEvent.ON_CRITICAL:owner=sourceId;break;}return string.IsNullOrWhiteSpace(owner)?resolved:resolved.Where(x=>string.Equals(x.ownerId,owner,StringComparison.Ordinal)).ToList();}
  static BattleTriggerContext Context(ResolvedHitSaveRecord hit,string skillId=null,TriggerActionContext actionContext=null,bool blocked=false,bool targetDied=false)=>new BattleTriggerContext{actionId=hit?.actionId,sourceId=hit?.sourceId,actionSourceId=hit?.sourceId,targetId=hit?.targetId,skillId=skillId,hitIndex=hit?.hitIndex??0,judgement=hit?.judgement,actualHpLoss=hit==null?0:Math.Max(0,hit.actualHpLoss),blocked=blocked,targetDied=targetDied,actionContext=actionContext};
  public static void TickEffects(BattleActorSaveRecord actor){if(actor==null)throw new ArgumentNullException(nameof(actor));foreach(var e in actor.appliedEffects??new List<AppliedEffectSaveRecord>())if(!e.consumed&&e.remainingTicks>0)e.remainingTicks--;actor.appliedEffects?.RemoveAll(x=>x==null||x.consumed||x.remainingTicks<=0);}
  public static double PassiveProperty(IEnumerable<PassiveContribution> equipped,string property){var c=PassiveRuntime.Compile(equipped);if(!c.ok)throw new InvalidOperationException(c.reason);return PassiveRuntime.SumProperty(c,property);}
  public static IReadOnlyDictionary<string,int> BuildFixedOrder(BattleSnapshotSaveRecord snapshot){var d=new Dictionary<string,int>(StringComparer.Ordinal);if(snapshot?.fixedActorOrder==null)return d;for(var i=0;i<snapshot.fixedActorOrder.Count;i++)d[snapshot.fixedActorOrder[i]]=i;return d;}
 }
}
