using System;
using System.Collections.Generic;
using System.Linq;
using GuildAdventure.Game.Save;
using GuildAdventure.Game.Core;
using GuildAdventure.Game.AI;
using GuildAdventure.Game.Skills;
namespace GuildAdventure.Game.Battle
{
 public sealed class BattleTickOptions{public IEnumerable<TriggerRegistration> triggerRegistrations;public TriggerActionContext actionContext;public IRandomSource passiveTriggerRng;public Func<ReactiveTriggerRequest,int,int,int?> executeFatalReactive;public Func<BattleActorSaveRecord,FormalAiBattleContext> resolveAi;public Func<string,SkillDefinition> resolveSkillById;public Func<BattleActorSaveRecord,ActionReservationSaveRecord,SkillDefinition,BattleAttackProposal> buildReservedAttack;public IRandomSource criticalRng,hitRng,blockRng;}
 public sealed class BattleTickResult{public bool ok=true;public string reason;public int tick;public List<string> expiredEffects=new List<string>(),dotSources=new List<string>(),aiEvaluated=new List<string>(),actionsStarted=new List<string>(),actionsSkipped=new List<string>(),castsCompleted=new List<string>();public int dotHpLoss,barrierAbsorbed,fatalPrevented;}
 public static class BattleTickRuntime
 {
  public static BattleTickResult Advance(BattleSnapshotSaveRecord snapshot)=>Advance(snapshot,null);
  public static BattleTickResult Advance(BattleSnapshotSaveRecord snapshot,BattleTickOptions options){if(snapshot==null)return Fail("BATTLE_TICK_SNAPSHOT_MISSING");var validation=BattleSnapshotValidation.Validate(snapshot);if(validation!=null)return Fail(validation);var result=new BattleTickResult{tick=snapshot.tick};var gaugeSettings=new ActionGaugeSettings();var fixedOrder=BattleEffectLifecycle.BuildFixedOrder(snapshot);var context=options?.actionContext??new TriggerActionContext{actionId="TICK:"+snapshot.tick};foreach(var id in snapshot.fixedActorOrder){var actor=snapshot.actors.Find(x=>x.actorId==id);if(actor==null)continue;TickPeriodic(actor,result,options,context,fixedOrder);TickCooldowns(actor);ExpireEffects(actor,result);AdvanceCast(snapshot,actor,result,options);var gauge=new ActionGaugeState{actorId=actor.actorId,gauge=actor.actionGauge,agi=actor.speed,alive=actor.alive&&actor.hp>0,casting=actor.cast?.active??false};ActionGauge.Advance(gauge,gaugeSettings);actor.actionGauge=gauge.gauge;TryAiAction(snapshot,actor,result,options);}snapshot.tick++;result.tick=snapshot.tick;return result;}
  static void AdvanceCast(BattleSnapshotSaveRecord snapshot,BattleActorSaveRecord actor,BattleTickResult result,BattleTickOptions options){var cast=actor.cast;if(cast==null||!cast.active)return;cast.remainingTicks=Math.Max(0,cast.remainingTicks-1);if(cast.remainingTicks>0)return;cast.active=false;var reservation=snapshot.actionReservations.FirstOrDefault(x=>x.reservationId==cast.reservationId);if(reservation==null){result.actionsSkipped.Add(actor.actorId+":CAST_RESERVATION_MISSING");return;}var skill=options?.resolveSkillById?.Invoke(reservation.skillId);if(skill==null){result.actionsSkipped.Add(actor.actorId+":CAST_SKILL_MISSING");return;}var attack=options?.buildReservedAttack?.Invoke(actor,reservation,skill);if(attack==null){result.actionsSkipped.Add(actor.actorId+":CAST_ATTACK_PROPOSAL_MISSING");return;}var completed=SkillActionTransaction.CompleteCast(snapshot,actor,skill,attack,options.criticalRng,options.hitRng,options.blockRng);if(!completed.ok&&!completed.executionSkipped){result.actionsSkipped.Add(actor.actorId+":"+completed.reason);return;}if(completed.executionSkipped){result.actionsSkipped.Add(actor.actorId+":"+completed.reason);return;}result.castsCompleted.Add(actor.actorId+":"+skill.id);}
  static void TryAiAction(BattleSnapshotSaveRecord snapshot,BattleActorSaveRecord actor,BattleTickResult result,BattleTickOptions options){if(options?.resolveAi==null||!actor.alive||actor.hp<=0||(actor.cast?.active??false)||actor.actionGauge<new ActionGaugeSettings().maxGauge)return;var ai=options.resolveAi(actor);if(ai==null)return;result.aiEvaluated.Add(actor.actorId);var decision=FormalAiBattleBridge.Decide(snapshot,actor,ai);if(!decision.ok){result.actionsSkipped.Add(actor.actorId+":"+decision.reason);return;}var action=SkillActionTransaction.Execute(snapshot,decision.request,options.criticalRng,options.hitRng,options.blockRng);if(!action.ok){result.actionsSkipped.Add(actor.actorId+":"+action.reason);return;}result.actionsStarted.Add(actor.actorId+":"+decision.request.skill.id+(action.castingStarted?":CAST":":INSTANT"));}
  static void TickPeriodic(BattleActorSaveRecord actor,BattleTickResult result,BattleTickOptions options,TriggerActionContext context,IReadOnlyDictionary<string,int> fixedOrder){foreach(var e in (actor.appliedEffects??new List<AppliedEffectSaveRecord>()).Where(x=>x!=null&&!x.consumed&&x.remainingTicks>0).OrderBy(x=>x.appliedTick).ThenBy(x=>x.sequence).ThenBy(x=>x.instanceId,StringComparer.Ordinal)){if(e.kind==EffectLifecycleKind.DOT.ToString()&&actor.alive&&actor.hp>0){var damage=EffectLifecycleRuntime.DotDamage(e.value);var ordered=(actor.barrierLayers??new List<BarrierLayerSaveRecord>()).OrderBy(x=>x.appliedTick).ThenBy(x=>x.sequence).ThenBy(x=>x.id,StringComparer.Ordinal).ToList();var runtime=ordered.Select(x=>new BarrierLayer{id=x.id,remaining=x.remaining}).ToList();var barrier=DamageDefense.ConsumeBarrierFifo(damage,runtime);result.barrierAbsorbed+=barrier.absorbed;var remaining=barrier.layers.ToDictionary(x=>x.id,x=>x.remaining,StringComparer.Ordinal);actor.barrierLayers=ordered.Where(x=>remaining.ContainsKey(x.id)&&remaining[x.id]>0).Select(x=>{x.remaining=remaining[x.id];return x;}).ToList();Func<int,int,int?> fatal=null;if(options?.executeFatalReactive!=null)fatal=(before,projected)=>{var fr=FatalDamageTriggerRuntime.Resolve(before,projected,e.sourceId,e.sourceId,actor.actorId,e.effectId,0,options.triggerRegistrations,fixedOrder,context,options.passiveTriggerRng,options.executeFatalReactive);if(fr.prevented)result.fatalPrevented++;return fr.prevented?(int?)fr.hpAfter:null;};var hp=DamageDefense.CommitHp(actor.hp,barrier.hpDamageCandidate,fatal);actor.hp=hp.hpAfter;actor.alive=actor.hp>0;result.dotHpLoss+=hp.actualHpLoss;result.dotSources.Add(e.instanceId);}e.remainingTicks--;}}
  static void TickCooldowns(BattleActorSaveRecord actor){foreach(var c in actor.cooldowns??new List<CooldownSaveRecord>())if(c!=null&&c.remainingTicks>0)c.remainingTicks--;actor.cooldowns?.RemoveAll(x=>x==null||x.remainingTicks<=0);}
  static void ExpireEffects(BattleActorSaveRecord actor,BattleTickResult result){var expired=(actor.appliedEffects??new List<AppliedEffectSaveRecord>()).Where(x=>x==null||x.consumed||x.remainingTicks<=0).ToList();foreach(var e in expired)if(e!=null)result.expiredEffects.Add(e.instanceId);actor.appliedEffects?.RemoveAll(x=>x==null||x.consumed||x.remainingTicks<=0);}
  static BattleTickResult Fail(string reason)=>new BattleTickResult{ok=false,reason=reason};
 }
}
