using System;
using System.Collections.Generic;
using System.Linq;
using GuildAdventure.Game.Save;
using GuildAdventure.Game.Core;
using GuildAdventure.Game.AI;
using GuildAdventure.Game.Skills;
namespace GuildAdventure.Game.Battle
{
 public sealed class BattleTickOptions{public IEnumerable<TriggerRegistration> triggerRegistrations;public TriggerActionContext actionContext;public IRandomSource passiveTriggerRng;public Func<ReactiveTriggerRequest,int,int,int?> executeFatalReactive;public Action<ReactiveTriggerRequest> executeReactive;public Func<BattleActorSaveRecord,FormalAiBattleContext> resolveAi;public Func<BattleActorSaveRecord,PassiveCompileResult> resolvePassives;public Func<string,SkillDefinition> resolveSkillById;public Func<BattleActorSaveRecord,ActionReservationSaveRecord,SkillDefinition,BattleAttackProposal> buildReservedAttack;public Func<BattleActorSaveRecord,ActionReservationSaveRecord,SkillDefinition,string,BattleAttackProposal> buildReservedTargetAttack;public IRandomSource criticalRng,hitRng,blockRng;}
 public sealed class BattleTickResult{public bool ok=true;public string reason;public int tick;public List<string> expiredEffects=new List<string>(),dotSources=new List<string>(),passiveRecovered=new List<string>(),aiEvaluated=new List<string>(),actionsStarted=new List<string>(),actionsSkipped=new List<string>(),castsCompleted=new List<string>();public List<BattleTriggerDispatch> triggerDispatches=new List<BattleTriggerDispatch>();public int dotHpLoss,passiveRecoveryAmount,barrierAbsorbed,fatalPrevented,reactiveExecuted,reactiveSkipped;public string reactiveStopReason;}
 public static class BattleTickRuntime
 {
  public static BattleTickResult Advance(BattleSnapshotSaveRecord snapshot)=>Advance(snapshot,null);
  public static BattleTickResult Advance(BattleSnapshotSaveRecord snapshot,BattleTickOptions options){if(snapshot==null)return Fail("BATTLE_TICK_SNAPSHOT_MISSING");var validation=BattleSnapshotValidation.Validate(snapshot);if(validation!=null)return Fail(validation);var result=new BattleTickResult{tick=snapshot.tick};var gaugeSettings=new ActionGaugeSettings();var fixedOrder=BattleEffectLifecycle.BuildFixedOrder(snapshot);var context=options?.actionContext??new TriggerActionContext{actionId="TICK:"+snapshot.tick};if(snapshot.tick==0)DispatchLifecycle(snapshot,TriggerEvent.ON_BATTLE_START,result,options,context);DispatchLifecycle(snapshot,TriggerEvent.ON_TURN_START,result,options,context);DispatchLifecycle(snapshot,TriggerEvent.WHILE_SOURCE_ALIVE,result,options,context);foreach(var id in snapshot.fixedActorOrder){var actor=snapshot.actors.Find(x=>x.actorId==id);if(actor==null)continue;TickPeriodic(snapshot,actor,result,options,context,fixedOrder);if(!actor.alive||actor.hp<=0){EffectLifecycleRuntime.CleanupOnDeath(actor);continue;}TickPassiveRecovery(snapshot,actor,result,options);TickCooldowns(actor);ExpireEffects(actor,result);AdvanceCast(snapshot,actor,result,options);var before=actor.actionGauge;var gauge=new ActionGaugeState{actorId=actor.actorId,gauge=before,agi=actor.speed,alive=actor.alive&&actor.hp>0,casting=actor.cast?.active??false};ActionGauge.Advance(gauge,gaugeSettings);actor.actionGauge=gauge.gauge;ReevaluateAiThresholds(snapshot,actor,before,result,options,gaugeSettings);TryAiAction(snapshot,actor,result,options);}DispatchLifecycle(snapshot,TriggerEvent.ON_TURN_END,result,options,context);snapshot.tick++;result.tick=snapshot.tick;return result;}
  static void DispatchLifecycle(BattleSnapshotSaveRecord snapshot,TriggerEvent trigger,BattleTickResult result,BattleTickOptions options,TriggerActionContext context){if(options?.triggerRegistrations==null)return;var r=BattleLifecycleTriggerRuntime.Dispatch(snapshot,trigger,options.triggerRegistrations,context,options.passiveTriggerRng,options.executeReactive);result.triggerDispatches.AddRange(r.dispatches);result.reactiveExecuted+=r.reactiveExecuted;result.reactiveSkipped+=r.reactiveSkipped;if(!r.ok)result.reactiveStopReason=r.reason;}
  static void TickPassiveRecovery(BattleSnapshotSaveRecord snapshot,BattleActorSaveRecord actor,BattleTickResult result,BattleTickOptions options){if(options?.resolvePassives==null)return;var compiled=options.resolvePassives(actor);var recovered=PassiveRuntime.RecoverPeriodic(actor,compiled,snapshot.tick);if(recovered<=0)return;result.passiveRecoveryAmount+=recovered;result.passiveRecovered.Add(actor.actorId+":"+recovered);}
  static void ReevaluateAiThresholds(BattleSnapshotSaveRecord snapshot,BattleActorSaveRecord actor,double before,BattleTickResult result,BattleTickOptions options,ActionGaugeSettings settings){if(options?.resolveAi==null||!actor.alive||actor.hp<=0||(actor.cast?.active??false)||actor.actionGauge<=before)return;var step=settings.maxGauge*settings.aiReevaluationRatio;if(step<=0)return;var first=(int)Math.Floor(before/step)+1;var last=(int)Math.Floor(actor.actionGauge/step);for(var n=first;n<=last;n++){var threshold=Math.Min(settings.maxGauge,n*step);if(threshold>=settings.maxGauge)break;var ai=options.resolveAi(actor);if(ai==null)continue;var graph=FormalAiBattleBridge.Reevaluate(ai);result.aiEvaluated.Add(actor.actorId+":"+threshold.ToString("0.##"));if(!graph.ok)result.actionsSkipped.Add(actor.actorId+":"+graph.reason);}}
  static void AdvanceCast(BattleSnapshotSaveRecord snapshot,BattleActorSaveRecord actor,BattleTickResult result,BattleTickOptions options){var cast=actor.cast;if(cast==null||!cast.active)return;cast.remainingTicks=Math.Max(0,cast.remainingTicks-1);if(cast.remainingTicks>0)return;cast.active=false;var reservation=snapshot.actionReservations.FirstOrDefault(x=>x.reservationId==cast.reservationId);if(reservation==null){result.actionsSkipped.Add(actor.actorId+":CAST_RESERVATION_MISSING");return;}var skill=options?.resolveSkillById?.Invoke(reservation.skillId);if(skill==null){result.actionsSkipped.Add(actor.actorId+":CAST_SKILL_MISSING");return;}var attack=options?.buildReservedAttack?.Invoke(actor,reservation,skill);if(attack==null){result.actionsSkipped.Add(actor.actorId+":CAST_ATTACK_PROPOSAL_MISSING");return;}Func<string,BattleAttackProposal> perTarget=null;if(options?.buildReservedTargetAttack!=null)perTarget=id=>options.buildReservedTargetAttack(actor,reservation,skill,id);var completed=SkillActionTransaction.CompleteCast(snapshot,actor,skill,attack,perTarget,options.criticalRng,options.hitRng,options.blockRng);if(!completed.ok&&!completed.executionSkipped){result.actionsSkipped.Add(actor.actorId+":"+completed.reason);return;}if(completed.executionSkipped){result.actionsSkipped.Add(actor.actorId+":"+completed.reason);return;}result.castsCompleted.Add(actor.actorId+":"+skill.id);}
  static void TryAiAction(BattleSnapshotSaveRecord snapshot,BattleActorSaveRecord actor,BattleTickResult result,BattleTickOptions options){if(options?.resolveAi==null||!actor.alive||actor.hp<=0||(actor.cast?.active??false)||actor.actionGauge<new ActionGaugeSettings().maxGauge)return;var ai=options.resolveAi(actor);if(ai==null)return;result.aiEvaluated.Add(actor.actorId+":100");var decision=FormalAiBattleBridge.Decide(snapshot,actor,ai);if(!decision.ok){result.actionsSkipped.Add(actor.actorId+":"+decision.reason);return;}var action=SkillActionTransaction.Execute(snapshot,decision.request,options.criticalRng,options.hitRng,options.blockRng);if(!action.ok){result.actionsSkipped.Add(actor.actorId+":"+action.reason);return;}result.actionsStarted.Add(actor.actorId+":"+decision.request.skill.id+(action.castingStarted?":CAST":":INSTANT"));}
  static void TickPeriodic(BattleSnapshotSaveRecord snapshot,BattleActorSaveRecord actor,BattleTickResult result,BattleTickOptions options,TriggerActionContext context,IReadOnlyDictionary<string,int> fixedOrder){foreach(var e in (actor.appliedEffects??new List<AppliedEffectSaveRecord>()).Where(x=>x!=null&&!x.consumed&&x.remainingTicks>0).OrderBy(x=>x.appliedTick).ThenBy(x=>x.sequence).ThenBy(x=>x.instanceId,StringComparer.Ordinal)){if(e.kind==EffectLifecycleKind.DOT.ToString()&&actor.alive&&actor.hp>0){Func<int,int,int?> fatal=null;if(options?.executeFatalReactive!=null)fatal=(beforeHp,projected)=>{var fr=FatalDamageTriggerRuntime.Resolve(beforeHp,projected,e.sourceId,e.sourceId,actor.actorId,e.effectId,0,options.triggerRegistrations,fixedOrder,context,options.passiveTriggerRng,options.executeFatalReactive);if(fr.prevented)result.fatalPrevented++;return fr.prevented?(int?)fr.hpAfter:null;};var damage=BattleDamageRuntime.Commit(actor,EffectLifecycleRuntime.DotDamage(e.value),fatal,true);result.barrierAbsorbed+=damage.barrierAbsorbed;result.dotHpLoss+=damage.actualHpLoss;result.dotSources.Add(e.instanceId);if(damage.actualHpLoss>0){var dispatches=new List<BattleTriggerDispatch>{BattleEffectLifecycle.DispatchEvent(TriggerEvent.ON_DAMAGE_DEALT,e.sourceId,actor.actorId,options?.triggerRegistrations,fixedOrder,context.actionId,e.effectId,context,e.sourceId)};if(damage.died)dispatches.Add(BattleEffectLifecycle.DispatchEvent(TriggerEvent.ON_DEATH,e.sourceId,actor.actorId,options?.triggerRegistrations,fixedOrder,context.actionId,e.effectId,context,e.sourceId));result.triggerDispatches.AddRange(dispatches);TriggerActivationRuntime.EnqueueBatch(context,dispatches);var drain=TriggerActivationRuntime.Drain(context,options?.passiveTriggerRng,options?.executeReactive);result.reactiveExecuted+=drain.executed;result.reactiveSkipped+=drain.skipped;if(!drain.ok)result.reactiveStopReason=drain.reason;}}e.remainingTicks--;if(!actor.alive||actor.hp<=0)break;}}
  static void TickCooldowns(BattleActorSaveRecord actor){foreach(var c in actor.cooldowns??new List<CooldownSaveRecord>())if(c!=null&&c.remainingTicks>0&&c.remainingTicks!=EffectLifecycleRuntime.PermanentBattleCooldown)c.remainingTicks--;actor.cooldowns?.RemoveAll(x=>x==null||x.remainingTicks<=0);}
  static void ExpireEffects(BattleActorSaveRecord actor,BattleTickResult result){var expired=(actor.appliedEffects??new List<AppliedEffectSaveRecord>()).Where(x=>x==null||x.consumed||x.remainingTicks<=0).ToList();foreach(var e in expired)if(e!=null)result.expiredEffects.Add(e.instanceId);actor.appliedEffects?.RemoveAll(x=>x==null||x.consumed||x.remainingTicks<=0);EffectLifecycleRuntime.CleanupBarrierLayers(actor);}
  static BattleTickResult Fail(string reason)=>new BattleTickResult{ok=false,reason=reason};
 }
}
