using System;
using System.Collections.Generic;
using System.Linq;
using GuildAdventure.Game.Core;
using GuildAdventure.Game.Save;
using GuildAdventure.Game.Skills;
namespace GuildAdventure.Game.Battle
{
 public sealed class MultiTargetAttackRequest{public ActionReservationSaveRecord reservation;public IEnumerable<string> executionTargetIds;public Func<string,BattleAttackProposal> buildAttack;public IEnumerable<CoverContract> coverContracts;}
 public sealed class MultiTargetBattleResult{public bool ok;public string reason;public readonly List<string> executedTargetIds=new List<string>();public readonly List<string> skippedTargetIds=new List<string>();public readonly List<BattleStepResult> targetResults=new List<BattleStepResult>();}
 public static class MultiTargetBattleExecutor
 {
  public static MultiTargetBattleResult Execute(BattleSnapshotSaveRecord snapshot,MultiTargetAttackRequest request,IRandomSource criticalRng,IRandomSource hitRng,IRandomSource blockRng){if(snapshot==null||request==null||request.reservation==null||request.buildAttack==null)return Fail("MULTI_TARGET_INPUT_INVALID");var reservation=request.reservation;if(reservation.fixedTargetIds==null||reservation.fixedTargetIds.Count==0)return Fail("MULTI_TARGET_FIXED_TARGETS_EMPTY");var canonical=snapshot.actionReservations.Find(x=>x!=null&&x.reservationId==reservation.reservationId);if(canonical!=null&&(canonical.actorId!=reservation.actorId||canonical.skillId!=reservation.skillId))return Fail("MULTI_TARGET_RESERVATION_MISMATCH");var executionReservation=canonical??reservation;var targets=(request.executionTargetIds??reservation.fixedTargetIds).Where(x=>!string.IsNullOrWhiteSpace(x)).ToList();if(targets.Count==0)return Fail("MULTI_TARGET_EXECUTION_TARGETS_EMPTY");foreach(var id in targets)if(!reservation.fixedTargetIds.Contains(id))return Fail("MULTI_TARGET_TARGET_NOT_RESERVED");var result=new MultiTargetBattleResult{ok=true};var range=SkillTargetRange.SINGLE;var hasRange=reservation.hasTargetContract&&Enum.TryParse(reservation.targetRange,true,out range);foreach(var fixedTargetId in targets){var actor=snapshot.actors.Find(x=>x.actorId==fixedTargetId);if(actor==null||!actor.alive||actor.hp<=0){result.skippedTargetIds.Add(fixedTargetId);continue;}var targetId=fixedTargetId;if(hasRange){var cover=CoverRuntime.Resolve(snapshot,fixedTargetId,range,request.coverContracts);if(!cover.ok){result.ok=false;result.reason=cover.reason;return result;}targetId=cover.targetId;}var target=snapshot.actors.Find(x=>x.actorId==targetId);if(target==null||!target.alive||target.hp<=0){result.skippedTargetIds.Add(fixedTargetId);continue;}var p=request.buildAttack(targetId);if(p==null){result.ok=false;result.reason="MULTI_TARGET_PROPOSAL_MISSING";return result;}p.reservationId=executionReservation.reservationId;p.sourceId=executionReservation.actorId;p.skillId=executionReservation.skillId;p.reservedTargetId=fixedTargetId;p.targetId=targetId;var step=BattleStepExecutor.ExecuteAttack(snapshot,p,executionReservation,criticalRng,hitRng,blockRng);if(!step.ok){result.ok=false;result.reason=step.reason;return result;}result.executedTargetIds.Add(targetId);result.targetResults.Add(step);var source=snapshot.actors.Find(x=>x.actorId==executionReservation.actorId);if(source==null||!source.alive||source.hp<=0)break;}return result;}
  static MultiTargetBattleResult Fail(string r)=>new MultiTargetBattleResult{ok=false,reason=r};
 }
}
