using System;
using System.Collections.Generic;
using System.Linq;
using GuildAdventure.Game.Core;
using GuildAdventure.Game.Save;
using GuildAdventure.Game.Skills;
namespace GuildAdventure.Game.Battle
{
 public sealed class SkillActionRequest{public SkillDefinition skill;public BattleAttackProposal attack;public List<string> fixedTargetIds;public Func<string,BattleAttackProposal> buildAttack;}
 public sealed class SkillActionResult{public bool ok;public string reason;public bool castingStarted,executionSkipped;public BattleStepResult battleStep;public MultiTargetBattleResult multiTargetStep;public ActionReservationSaveRecord reservation;}
 public static class SkillActionTransaction
 {
  public static SkillActionResult Execute(BattleSnapshotSaveRecord snapshot,SkillActionRequest request,IRandomSource criticalRng,IRandomSource hitRng,IRandomSource blockRng){var precheck=Precheck(snapshot,request);if(!precheck.ok)return precheck;var actor=snapshot.actors.First(x=>x.actorId==request.attack.sourceId);var reservation=precheck.reservation;snapshot.actionReservations.Add(reservation);if(request.skill.castTicks>0){actor.cast=new CastSaveRecord{reservationId=reservation.reservationId,skillId=reservation.skillId,targetId=reservation.fixedTargetIds.FirstOrDefault(),startTick=reservation.startTick,completeTick=reservation.completeTick,remainingTicks=Math.Max(0,reservation.completeTick-snapshot.tick),active=true,fixedTargetIds=new List<string>(reservation.fixedTargetIds),usageConditions=reservation.usageConditions};return new SkillActionResult{ok=true,castingStarted=true,reservation=reservation};}return ExecuteReserved(snapshot,request.skill,request.attack,reservation,criticalRng,hitRng,blockRng,request.buildAttack);}
  public static SkillActionResult CompleteCast(BattleSnapshotSaveRecord snapshot,BattleActorSaveRecord actor,SkillDefinition skill,BattleAttackProposal attack,IRandomSource criticalRng,IRandomSource hitRng,IRandomSource blockRng){if(snapshot==null||actor==null||skill==null||attack==null)return Fail("CAST_COMPLETION_INPUT_INVALID");var cast=actor.cast;if(cast==null||cast.active||cast.remainingTicks>0)return Fail("CAST_NOT_COMPLETE");var reservation=snapshot.actionReservations.FirstOrDefault(x=>x.reservationId==cast.reservationId);if(reservation==null)return Fail("CAST_RESERVATION_MISSING");return ExecuteReserved(snapshot,skill,attack,reservation,criticalRng,hitRng,blockRng,null);}
  public static SkillActionResult Precheck(BattleSnapshotSaveRecord snapshot,SkillActionRequest request){if(snapshot==null||request==null||request.skill==null||request.attack==null)return Fail("SKILL_ACTION_INPUT_INVALID");var actor=snapshot.actors.FirstOrDefault(x=>x.actorId==request.attack.sourceId);if(actor==null)return Fail("SKILL_ACTION_ACTOR_MISSING");if(actor.actionGauge<new ActionGaugeSettings().maxGauge)return Fail("ACTION_GAUGE_NOT_READY");if(actor.cast!=null&&actor.cast.active)return Fail("CAST_ALREADY_ACTIVE");if(actor.cooldowns.Any(x=>x.skillId==request.skill.id&&x.remainingTicks>0))return Fail("SKILL_COOLDOWN_ACTIVE");if(string.IsNullOrWhiteSpace(request.attack.reservationId))return Fail("ACTION_RESERVATION_ID_MISSING");if(snapshot.actionReservations.Any(x=>x.reservationId==request.attack.reservationId))return Fail("ACTION_RESERVATION_ID_DUPLICATE");var ids=(request.fixedTargetIds!=null&&request.fixedTargetIds.Count>0?request.fixedTargetIds:new List<string>{request.attack.targetId}).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.Ordinal).ToList();if(ids.Count==0)return Fail("TARGET_INVALID_AT_PRECHECK");foreach(var id in ids){var t=snapshot.actors.FirstOrDefault(x=>x.actorId==id);if(t==null||!t.alive||t.hp<=0)return Fail("TARGET_INVALID_AT_PRECHECK");}var check=SkillUseCondition.CanUse(request.skill,ToRuntimeActor(actor));if(!check.ok)return Fail(check.reason);return new SkillActionResult{ok=true,reservation=new ActionReservationSaveRecord{reservationId=request.attack.reservationId,actorId=actor.actorId,skillId=request.skill.id,startTick=snapshot.tick,completeTick=snapshot.tick+Math.Max(0,request.skill.castTicks),fixedTargetIds=ids,usageConditions=new UsageConditionsSaveRecord()}};}
  static SkillActionResult ExecuteReserved(BattleSnapshotSaveRecord snapshot,SkillDefinition skill,BattleAttackProposal attack,ActionReservationSaveRecord reservation,IRandomSource criticalRng,IRandomSource hitRng,IRandomSource blockRng,Func<string,BattleAttackProposal> buildAttack){var actor=snapshot.actors.FirstOrDefault(x=>x.actorId==reservation.actorId);if(actor==null)return Fail("SKILL_ACTION_ACTOR_MISSING");var runtimeActor=ToRuntimeActor(actor);var executionCheck=SkillUseCondition.CanUse(skill,runtimeActor);if(!executionCheck.ok){ConsumeGauge(actor,false);return new SkillActionResult{ok=false,reason=executionCheck.reason,reservation=reservation};}var valid=reservation.fixedTargetIds.Where(id=>snapshot.actors.Any(x=>x.actorId==id&&x.alive&&x.hp>0)).ToList();if(valid.Count==0){ConsumeGauge(actor,false);return new SkillActionResult{ok=true,executionSkipped=true,reason="TARGET_INVALID_AT_EFFECT_START",reservation=reservation};}if(skill.resource==SkillResourceKind.HP&&skill.resourceCost>0)return Fail("HP_COST_NOT_SUPPORTED_BY_FORMAL_RUNTIME");var mpBefore=actor.mp;var cooldownBefore=actor.cooldowns.Select(x=>new CooldownSaveRecord{skillId=x.skillId,remainingTicks=x.remainingTicks}).ToList();SkillUseCondition.PayCost(skill,runtimeActor);actor.mp=runtimeActor.mp;StartCooldown(actor,skill);if(reservation.fixedTargetIds.Count>1){var multi=MultiTargetBattleExecutor.Execute(snapshot,new MultiTargetAttackRequest{reservation=reservation,buildAttack=buildAttack??(id=>CloneAttack(attack))},criticalRng,hitRng,blockRng);if(!multi.ok){actor.mp=mpBefore;actor.cooldowns=cooldownBefore;return Fail(multi.reason);}ConsumeGauge(actor,true);return new SkillActionResult{ok=true,multiTargetStep=multi,reservation=reservation};}attack.reservationId=reservation.reservationId;attack.sourceId=reservation.actorId;attack.skillId=reservation.skillId;attack.targetId=valid[0];var step=BattleStepExecutor.ExecuteAttack(snapshot,attack,reservation,criticalRng,hitRng,blockRng);if(!step.ok){actor.mp=mpBefore;actor.cooldowns=cooldownBefore;return Fail(step.reason);}ConsumeGauge(actor,true);return new SkillActionResult{ok=true,battleStep=step,reservation=reservation};}
  static BattleAttackProposal CloneAttack(BattleAttackProposal p)=>new BattleAttackProposal{hitCount=p.hitCount,damageType=p.damageType,criticalRatePercent=p.criticalRatePercent,accuracy=p.accuracy,evasion=p.evasion,magicAccuracy=p.magicAccuracy,magicResistance=p.magicResistance,baseDamage=p.baseDamage,damageResistance=p.damageResistance,criticalBonusDamagePercent=p.criticalBonusDamagePercent,criticalBonusReduction=p.criticalBonusReduction,formationMultiplier=p.formationMultiplier,randomMultiplier=p.randomMultiplier,elementShares=p.elementShares,elementResistances=p.elementResistances,blockEligible=p.blockEligible,blockRate=p.blockRate,blockCutRate=p.blockCutRate,fatalResolver=p.fatalResolver,executeFatalReactive=p.executeFatalReactive,hpAbsorbRate=p.hpAbsorbRate,mpAbsorbRate=p.mpAbsorbRate,reflectionRate=p.reflectionRate,triggerRegistrations=p.triggerRegistrations,triggerActionContext=p.triggerActionContext,passiveTriggerRng=p.passiveTriggerRng,executeReactive=p.executeReactive};
  static void ConsumeGauge(BattleActorSaveRecord actor,bool success){var s=new ActionGaugeState{actorId=actor.actorId,gauge=actor.actionGauge,alive=actor.alive};var cfg=new ActionGaugeSettings();if(success)ActionGauge.ConsumeSuccessful(s,cfg);else ActionGauge.ConsumeFailedExecution(s,cfg);actor.actionGauge=s.gauge;}
  public static bool AdvanceCastAndCooldowns(BattleActorSaveRecord actor){if(actor==null)throw new ArgumentNullException(nameof(actor));foreach(var c in actor.cooldowns)c.remainingTicks=Math.Max(0,c.remainingTicks-1);actor.cooldowns.RemoveAll(x=>x.remainingTicks<=0);if(actor.cast==null||!actor.cast.active)return false;actor.cast.remainingTicks=Math.Max(0,actor.cast.remainingTicks-1);if(actor.cast.remainingTicks==0){actor.cast.active=false;return true;}return false;}
  static SkillActorState ToRuntimeActor(BattleActorSaveRecord actor)=>new SkillActorState{actorId=actor.actorId,hp=actor.hp,maxHp=actor.maxHp,mp=actor.mp,maxMp=actor.maxMp,alive=actor.alive};
  static void StartCooldown(BattleActorSaveRecord actor,SkillDefinition skill){if(skill.cooldownTicks<=0)return;actor.cooldowns.RemoveAll(x=>x.skillId==skill.id);actor.cooldowns.Add(new CooldownSaveRecord{skillId=skill.id,remainingTicks=skill.cooldownTicks});}
  static SkillActionResult Fail(string reason)=>new SkillActionResult{ok=false,reason=reason};
 }
}
