using System;
using System.Collections.Generic;
using GuildAdventure.Game.Save;
using GuildAdventure.Game.Core;
namespace GuildAdventure.Game.Battle
{
 public enum SkillEffectKind{HEAL,APPLY,REMOVE,RESOURCE_CHANGE,REVIVE,TARGET_CONTROL}
 public sealed class SkillEffectRequest{public SkillEffectKind kind;public string sourceId,effectId,instanceId,actionSourceId;public EffectLifecycleKind lifecycleKind;public int durationTicks,sequence,maxStacks;public double power,statusResistancePercent,magicIncreaseMultiplier=1d;public int hpDelta,mpDelta;public bool normalCleanse=true;public IEnumerable<TriggerRegistration> triggerRegistrations;public TriggerActionContext triggerActionContext;public IRandomSource passiveTriggerRng;public Action<ReactiveTriggerRequest> executeReactive;}
 public sealed class SkillEffectResult{public bool ok;public string reason;public bool triggerOk=true;public string triggerReason;public int hpBefore,hpAfter,mpBefore,mpAfter;public AppliedEffectSaveRecord applied,removed;public BarrierLayerSaveRecord barrier;public List<BattleTriggerDispatch> triggerDispatches=new List<BattleTriggerDispatch>();public int reactiveExecuted,reactiveSkipped;}
 public static class SkillEffectRuntime
 {
  public static SkillEffectResult Execute(BattleSnapshotSaveRecord snapshot,BattleActorSaveRecord target,SkillEffectRequest r){if(snapshot==null||target==null||r==null)return Fail("SKILL_EFFECT_INPUT_INVALID");var wasAlive=target.alive&&target.hp>0;var result=new SkillEffectResult{ok=true,hpBefore=target.hp,mpBefore=target.mp};switch(r.kind){case SkillEffectKind.HEAL:if(!wasAlive)return Fail("SKILL_EFFECT_HEAL_TARGET_DEAD");target.hp=Math.Min(target.maxHp,target.hp+EffectLifecycleRuntime.HealAmount(target.maxHp,r.power,r.magicIncreaseMultiplier));break;case SkillEffectKind.APPLY:var request=new EffectApplyRequest{instanceId=r.instanceId,sourceId=r.sourceId,effectId=r.effectId,kind=r.lifecycleKind,baseDurationTicks=r.durationTicks,value=r.power,statusResistancePercent=r.statusResistancePercent,appliedTick=snapshot.tick,sequence=r.sequence,maxStacks=r.maxStacks};if(r.lifecycleKind==EffectLifecycleKind.BARRIER){var amount=EffectLifecycleRuntime.BarrierAmount(target.maxHp,r.power);var barrierApply=EffectLifecycleRuntime.ApplyBarrier(target,request,amount);if(!barrierApply.ok)return Fail(barrierApply.reason);result.applied=barrierApply.applied;result.barrier=target.barrierLayers.Find(x=>x.id==r.instanceId);break;}var applied=EffectLifecycleRuntime.Apply(target,request);if(!applied.ok)return Fail(applied.reason);result.applied=applied.applied;if(r.lifecycleKind==EffectLifecycleKind.STATUS)Dispatch(snapshot,target,r,result,TriggerEvent.ON_STATUS_APPLIED);break;case SkillEffectKind.REMOVE:result.removed=EffectLifecycleRuntime.RemoveOldestStatus(target,r.effectId,r.normalCleanse);if(result.removed==null)return Fail("SKILL_EFFECT_REMOVE_NOT_FOUND");break;case SkillEffectKind.RESOURCE_CHANGE:target.hp=Math.Max(0,Math.Min(target.maxHp,target.hp+r.hpDelta));target.mp=Math.Max(0,Math.Min(target.maxMp,target.mp+r.mpDelta));target.alive=target.hp>0;break;case SkillEffectKind.REVIVE:if(wasAlive)return Fail("SKILL_EFFECT_REVIVE_TARGET_ALIVE");target.hp=Math.Max(1,Math.Min(target.maxHp,EffectLifecycleRuntime.HealAmount(target.maxHp,r.power)));target.alive=true;break;case SkillEffectKind.TARGET_CONTROL:return Fail("SKILL_EFFECT_TARGET_CONTROL_NOT_IMPLEMENTED");default:return Fail("SKILL_EFFECT_KIND_UNSUPPORTED");}if(wasAlive&&(!target.alive||target.hp<=0))Dispatch(snapshot,target,r,result,TriggerEvent.ON_DEATH);result.hpAfter=target.hp;result.mpAfter=target.mp;return result;}
  static void Dispatch(BattleSnapshotSaveRecord snapshot,BattleActorSaveRecord target,SkillEffectRequest r,SkillEffectResult result,TriggerEvent e){var action=r.triggerActionContext??new TriggerActionContext{actionId="EFFECT:"+snapshot.tick+":"+r.sourceId+":"+target.actorId};var d=BattleEffectLifecycle.DispatchEvent(e,r.sourceId,target.actorId,r.triggerRegistrations,BattleEffectLifecycle.BuildFixedOrder(snapshot),action.actionId,r.effectId,action,r.actionSourceId);result.triggerDispatches.Add(d);TriggerActivationRuntime.Enqueue(action,d);var drain=TriggerActivationRuntime.Drain(action,r.passiveTriggerRng,r.executeReactive);result.reactiveExecuted+=drain.executed;result.reactiveSkipped+=drain.skipped;if(!drain.ok){result.triggerOk=false;result.triggerReason=drain.reason;}}
  static SkillEffectResult Fail(string reason)=>new SkillEffectResult{ok=false,reason=reason,triggerOk=true};
 }
}
