using System;
using System.Collections.Generic;
using System.Linq;
using GuildAdventure.Game.Core;
namespace GuildAdventure.Game.Battle
{
 public sealed class TriggerActivationHistory{public string passiveId,trigger,sourceId,targetId;public int ordinal;}
 public sealed class PreparedTriggerActivation{public TriggerActionContext action;public string passiveId,trigger,sourceId,targetId;public bool chancePassed,committed;}
 public sealed class ReactiveTriggerRequest{public TriggerRegistration registration;public BattleTriggerContext context;public long eventSequence,queueSequence;}
 public sealed class TriggerActionContext{public string actionId;public int activationCount;public int activationLimit=16;public long reactiveEventSequence,reactiveSequence;public readonly HashSet<string> executingKeys=new HashSet<string>(StringComparer.Ordinal);public readonly List<TriggerActivationHistory> history=new List<TriggerActivationHistory>();public readonly List<ReactiveTriggerRequest> reactiveQueue=new List<ReactiveTriggerRequest>();}
 public sealed class TriggerActivationResult{public bool ok;public string reason;public PreparedTriggerActivation prepared;}
 public sealed class ReactiveDrainResult{public bool ok=true;public string reason;public int executed,skipped;}
 public static class TriggerActivationRuntime
 {
  public const string LimitReached="TRIGGER_ACTION_LIMIT_REACHED",RngPurpose="PASSIVE_TRIGGER";
  public static TriggerActivationResult PrepareActivation(TriggerActionContext action,string passiveId,string trigger=null,string sourceId=null,string targetId=null){if(action==null)return Fail("TRIGGER_ACTION_CONTEXT_MISSING");if(string.IsNullOrWhiteSpace(passiveId))return Fail("TRIGGER_PASSIVE_ID_MISSING");var limit=action.activationLimit>0?action.activationLimit:16;if(action.activationCount>=limit)return Fail(LimitReached);if(action.executingKeys.Contains(passiveId))return Fail("TRIGGER_REENTRY_BLOCKED");return new TriggerActivationResult{ok=true,prepared=new PreparedTriggerActivation{action=action,passiveId=passiveId,trigger=trigger,sourceId=sourceId,targetId=targetId}};}
  public static TriggerActivationResult CanActivate(TriggerActionContext action,string passiveId)=>PrepareActivation(action,passiveId);
  public static TriggerActivationResult CheckChance(PreparedTriggerActivation prepared,double chance,IRandomSource rng){if(prepared==null||prepared.action==null)return Fail("TRIGGER_PREPARED_ACTIVATION_MISSING");if(double.IsNaN(chance)||double.IsInfinity(chance)||chance<0||chance>1)return Fail("TRIGGER_ACTIVATION_CHANCE_INVALID");if(chance==0)return Fail("ACTIVATION_CHANCE_ZERO");if(chance<1){if(rng==null)return Fail("TRIGGER_RNG_MISSING");var roll=rng.Next01(RngPurpose);if(double.IsNaN(roll)||double.IsInfinity(roll)||roll<0||roll>=1)return Fail("TRIGGER_RNG_RANGE");if(roll>=chance)return Fail("ACTIVATION_CHANCE_FAILED");}prepared.chancePassed=true;return new TriggerActivationResult{ok=true,prepared=prepared};}
  public static TriggerActivationResult CommitActivation(PreparedTriggerActivation prepared){if(prepared==null||prepared.action==null)return Fail("TRIGGER_PREPARED_ACTIVATION_MISSING");if(!prepared.chancePassed)return Fail("TRIGGER_CHANCE_NOT_PASSED");if(prepared.committed)return Fail("TRIGGER_ACTIVATION_ALREADY_COMMITTED");var can=PrepareActivation(prepared.action,prepared.passiveId,prepared.trigger,prepared.sourceId,prepared.targetId);if(!can.ok)return can;prepared.action.activationCount++;prepared.action.executingKeys.Add(prepared.passiveId);prepared.action.history.Add(new TriggerActivationHistory{passiveId=prepared.passiveId,trigger=prepared.trigger,sourceId=prepared.sourceId,targetId=prepared.targetId,ordinal=prepared.action.activationCount});prepared.committed=true;return new TriggerActivationResult{ok=true,prepared=prepared};}
  public static TriggerActivationResult TryActivate(TriggerActionContext action,string passiveId,double chance,IRandomSource rng,string trigger=null,string sourceId=null,string targetId=null){var p=PrepareActivation(action,passiveId,trigger,sourceId,targetId);if(!p.ok)return p;var c=CheckChance(p.prepared,chance,rng);if(!c.ok)return c;return CommitActivation(c.prepared);}
  public static void Release(TriggerActionContext action,string passiveId){if(action!=null&&!string.IsNullOrWhiteSpace(passiveId))action.executingKeys.Remove(passiveId);}
  public static void Enqueue(TriggerActionContext action,BattleTriggerDispatch dispatch){if(action==null||dispatch==null)return;var eventSequence=++action.reactiveEventSequence;foreach(var r in dispatch.registrations??new List<TriggerRegistration>())action.reactiveQueue.Add(new ReactiveTriggerRequest{registration=r,context=dispatch.context,eventSequence=eventSequence,queueSequence=++action.reactiveSequence});}
  public static ReactiveDrainResult Drain(TriggerActionContext action,IRandomSource rng,Action<ReactiveTriggerRequest> execute){var result=new ReactiveDrainResult();if(action==null){result.ok=false;result.reason="TRIGGER_ACTION_CONTEXT_MISSING";return result;}while(action.reactiveQueue.Count>0){var request=action.reactiveQueue.OrderBy(x=>x.eventSequence).ThenBy(x=>FamilyRank(x.registration?.trigger??TriggerEvent.ON_HIT_DEALT)).ThenByDescending(x=>x.registration?.priority??int.MinValue).ThenBy(x=>x.registration?.sequence??int.MaxValue).ThenBy(x=>x.queueSequence).First();action.reactiveQueue.Remove(request);var r=request.registration;if(r==null){result.skipped++;continue;}var prepared=PrepareActivation(action,r.id,r.trigger.ToString(),request.context?.sourceId,request.context?.targetId);if(!prepared.ok){if(prepared.reason==LimitReached){action.reactiveQueue.Clear();result.ok=false;result.reason=LimitReached;return result;}result.skipped++;continue;}var chance=CheckChance(prepared.prepared,r.activationChance,rng);if(!chance.ok){result.skipped++;continue;}var committed=CommitActivation(chance.prepared);if(!committed.ok){if(committed.reason==LimitReached){action.reactiveQueue.Clear();result.ok=false;result.reason=LimitReached;return result;}result.skipped++;continue;}try{TriggerRuntime.MarkConsumed(r);execute?.Invoke(request);result.executed++;}finally{Release(action,r.id);}}return result;}
  static int FamilyRank(TriggerEvent e)=>e==TriggerEvent.ON_HIT_RECEIVED?0:e==TriggerEvent.ON_ALLY_ATTACK?1:2;
  static TriggerActivationResult Ok()=>new TriggerActivationResult{ok=true};static TriggerActivationResult Fail(string reason)=>new TriggerActivationResult{ok=false,reason=reason};
 }
}
